// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: control_center.proto

package com.acmedcare.framework.devops.endpoint.center;

/**
 * Protobuf type {@code com.acmedcare.framework.devops.endpoint.center.HeartBeat}
 */
public  final class HeartBeat extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.acmedcare.framework.devops.endpoint.center.HeartBeat)
    HeartBeatOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HeartBeat.newBuilder() to construct.
  private HeartBeat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HeartBeat() {
    serviceName_ = "";
    ip_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new HeartBeat();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HeartBeat(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            serviceName_ = s;
            break;
          }
          case 16: {

            successCount_ = input.readInt32();
            break;
          }
          case 24: {

            failCount_ = input.readInt32();
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            ip_ = s;
            break;
          }
          case 40: {

            currentTime_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return  DevOpsProto.internal_static_com_acmedcare_framework_devops_endpoint_center_HeartBeat_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return  DevOpsProto.internal_static_com_acmedcare_framework_devops_endpoint_center_HeartBeat_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
             HeartBeat.class,  Builder.class);
  }

  public static final int SERVICENAME_FIELD_NUMBER = 1;
  private volatile Object serviceName_;
  /**
   * <code>string serviceName = 1;</code>
   * @return The serviceName.
   */
  public String getServiceName() {
    Object ref = serviceName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      serviceName_ = s;
      return s;
    }
  }
  /**
   * <code>string serviceName = 1;</code>
   * @return The bytes for serviceName.
   */
  public com.google.protobuf.ByteString
      getServiceNameBytes() {
    Object ref = serviceName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      serviceName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUCCESSCOUNT_FIELD_NUMBER = 2;
  private int successCount_;
  /**
   * <code>int32 successCount = 2;</code>
   * @return The successCount.
   */
  public int getSuccessCount() {
    return successCount_;
  }

  public static final int FAILCOUNT_FIELD_NUMBER = 3;
  private int failCount_;
  /**
   * <code>int32 failCount = 3;</code>
   * @return The failCount.
   */
  public int getFailCount() {
    return failCount_;
  }

  public static final int IP_FIELD_NUMBER = 4;
  private volatile Object ip_;
  /**
   * <code>string ip = 4;</code>
   * @return The ip.
   */
  public String getIp() {
    Object ref = ip_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      ip_ = s;
      return s;
    }
  }
  /**
   * <code>string ip = 4;</code>
   * @return The bytes for ip.
   */
  public com.google.protobuf.ByteString
      getIpBytes() {
    Object ref = ip_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      ip_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CURRENTTIME_FIELD_NUMBER = 5;
  private long currentTime_;
  /**
   * <code>int64 currentTime = 5;</code>
   * @return The currentTime.
   */
  public long getCurrentTime() {
    return currentTime_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getServiceNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, serviceName_);
    }
    if (successCount_ != 0) {
      output.writeInt32(2, successCount_);
    }
    if (failCount_ != 0) {
      output.writeInt32(3, failCount_);
    }
    if (!getIpBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, ip_);
    }
    if (currentTime_ != 0L) {
      output.writeInt64(5, currentTime_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getServiceNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, serviceName_);
    }
    if (successCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, successCount_);
    }
    if (failCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, failCount_);
    }
    if (!getIpBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, ip_);
    }
    if (currentTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, currentTime_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof  HeartBeat)) {
      return super.equals(obj);
    }
     HeartBeat other = ( HeartBeat) obj;

    if (!getServiceName()
        .equals(other.getServiceName())) return false;
    if (getSuccessCount()
        != other.getSuccessCount()) return false;
    if (getFailCount()
        != other.getFailCount()) return false;
    if (!getIp()
        .equals(other.getIp())) return false;
    if (getCurrentTime()
        != other.getCurrentTime()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SERVICENAME_FIELD_NUMBER;
    hash = (53 * hash) + getServiceName().hashCode();
    hash = (37 * hash) + SUCCESSCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getSuccessCount();
    hash = (37 * hash) + FAILCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getFailCount();
    hash = (37 * hash) + IP_FIELD_NUMBER;
    hash = (53 * hash) + getIp().hashCode();
    hash = (37 * hash) + CURRENTTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCurrentTime());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static  HeartBeat parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static  HeartBeat parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static  HeartBeat parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static  HeartBeat parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static  HeartBeat parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static  HeartBeat parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static  HeartBeat parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static  HeartBeat parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static  HeartBeat parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static  HeartBeat parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static  HeartBeat parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static  HeartBeat parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder( HeartBeat prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.acmedcare.framework.devops.endpoint.center.HeartBeat}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.acmedcare.framework.devops.endpoint.center.HeartBeat)
       com.acmedcare.framework.devops.endpoint.center.HeartBeatOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return  DevOpsProto.internal_static_com_acmedcare_framework_devops_endpoint_center_HeartBeat_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return  DevOpsProto.internal_static_com_acmedcare_framework_devops_endpoint_center_HeartBeat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
               HeartBeat.class,  Builder.class);
    }

    // Construct using  com.acmedcare.framework.devops.endpoint.center.HeartBeat.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      serviceName_ = "";

      successCount_ = 0;

      failCount_ = 0;

      ip_ = "";

      currentTime_ = 0L;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return  DevOpsProto.internal_static_com_acmedcare_framework_devops_endpoint_center_HeartBeat_descriptor;
    }

    @Override
    public  HeartBeat getDefaultInstanceForType() {
      return  HeartBeat.getDefaultInstance();
    }

    @Override
    public  HeartBeat build() {
       HeartBeat result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public  HeartBeat buildPartial() {
       HeartBeat result = new  HeartBeat(this);
      result.serviceName_ = serviceName_;
      result.successCount_ = successCount_;
      result.failCount_ = failCount_;
      result.ip_ = ip_;
      result.currentTime_ = currentTime_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof  HeartBeat) {
        return mergeFrom(( HeartBeat)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom( HeartBeat other) {
      if (other ==  HeartBeat.getDefaultInstance()) return this;
      if (!other.getServiceName().isEmpty()) {
        serviceName_ = other.serviceName_;
        onChanged();
      }
      if (other.getSuccessCount() != 0) {
        setSuccessCount(other.getSuccessCount());
      }
      if (other.getFailCount() != 0) {
        setFailCount(other.getFailCount());
      }
      if (!other.getIp().isEmpty()) {
        ip_ = other.ip_;
        onChanged();
      }
      if (other.getCurrentTime() != 0L) {
        setCurrentTime(other.getCurrentTime());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
       HeartBeat parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = ( HeartBeat) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object serviceName_ = "";
    /**
     * <code>string serviceName = 1;</code>
     * @return The serviceName.
     */
    public String getServiceName() {
      Object ref = serviceName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        serviceName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string serviceName = 1;</code>
     * @return The bytes for serviceName.
     */
    public com.google.protobuf.ByteString
        getServiceNameBytes() {
      Object ref = serviceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string serviceName = 1;</code>
     * @param value The serviceName to set.
     * @return This builder for chaining.
     */
    public Builder setServiceName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      serviceName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string serviceName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearServiceName() {

      serviceName_ = getDefaultInstance().getServiceName();
      onChanged();
      return this;
    }
    /**
     * <code>string serviceName = 1;</code>
     * @param value The bytes for serviceName to set.
     * @return This builder for chaining.
     */
    public Builder setServiceNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      serviceName_ = value;
      onChanged();
      return this;
    }

    private int successCount_ ;
    /**
     * <code>int32 successCount = 2;</code>
     * @return The successCount.
     */
    public int getSuccessCount() {
      return successCount_;
    }
    /**
     * <code>int32 successCount = 2;</code>
     * @param value The successCount to set.
     * @return This builder for chaining.
     */
    public Builder setSuccessCount(int value) {

      successCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 successCount = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSuccessCount() {

      successCount_ = 0;
      onChanged();
      return this;
    }

    private int failCount_ ;
    /**
     * <code>int32 failCount = 3;</code>
     * @return The failCount.
     */
    public int getFailCount() {
      return failCount_;
    }
    /**
     * <code>int32 failCount = 3;</code>
     * @param value The failCount to set.
     * @return This builder for chaining.
     */
    public Builder setFailCount(int value) {

      failCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 failCount = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFailCount() {

      failCount_ = 0;
      onChanged();
      return this;
    }

    private Object ip_ = "";
    /**
     * <code>string ip = 4;</code>
     * @return The ip.
     */
    public String getIp() {
      Object ref = ip_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string ip = 4;</code>
     * @return The bytes for ip.
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      Object ref = ip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ip = 4;</code>
     * @param value The ip to set.
     * @return This builder for chaining.
     */
    public Builder setIp(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      ip_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ip = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIp() {

      ip_ = getDefaultInstance().getIp();
      onChanged();
      return this;
    }
    /**
     * <code>string ip = 4;</code>
     * @param value The bytes for ip to set.
     * @return This builder for chaining.
     */
    public Builder setIpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      ip_ = value;
      onChanged();
      return this;
    }

    private long currentTime_ ;
    /**
     * <code>int64 currentTime = 5;</code>
     * @return The currentTime.
     */
    public long getCurrentTime() {
      return currentTime_;
    }
    /**
     * <code>int64 currentTime = 5;</code>
     * @param value The currentTime to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentTime(long value) {

      currentTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 currentTime = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentTime() {

      currentTime_ = 0L;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.acmedcare.framework.devops.endpoint.center.HeartBeat)
  }

  // @@protoc_insertion_point(class_scope:com.acmedcare.framework.devops.endpoint.center.HeartBeat)
  private static final  HeartBeat DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new  HeartBeat();
  }

  public static  HeartBeat getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HeartBeat>
      PARSER = new com.google.protobuf.AbstractParser<HeartBeat>() {
    @Override
    public HeartBeat parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HeartBeat(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HeartBeat> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<HeartBeat> getParserForType() {
    return PARSER;
  }

  @Override
  public  HeartBeat getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

