// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: control_center.proto

package com.acmedcare.framework.devops.endpoint.center;

public interface ResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.acmedcare.framework.devops.endpoint.center.Result)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string data = 2;</code>
   * @return The data.
   */
  String getData();
  /**
   * <code>string data = 2;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
