// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: controller.proto

package com.acmedcare.framework.starter.control.protobuf;

public final class DevOpsProto {
  private DevOpsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_acmedcare_framework_starter_control_protobuf_RequestDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_acmedcare_framework_starter_control_protobuf_RequestDto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_acmedcare_framework_starter_control_protobuf_ResultDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_acmedcare_framework_starter_control_protobuf_ResultDto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_acmedcare_framework_starter_control_protobuf_ServiceDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_acmedcare_framework_starter_control_protobuf_ServiceDto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020controller.proto\0220com.acmedcare.framew" +
      "ork.starter.control.protobuf\"\032\n\nRequestD" +
      "to\022\014\n\004data\030\001 \001(\t\"\034\n\tResultDto\022\017\n\007success" +
      "\030\001 \001(\010\"4\n\nServiceDto\022\014\n\004name\030\001 \001(\t\022\n\n\002ip" +
      "\030\002 \001(\t\022\014\n\004port\030\003 \001(\t2\260\004\n\020DevOpsControlle" +
      "r\022\204\001\n\005check\022<.com.acmedcare.framework.st" +
      "arter.control.protobuf.RequestDto\032;.com." +
      "acmedcare.framework.starter.control.prot" +
      "obuf.ResultDto\"\000\022\204\001\n\005start\022<.com.acmedca" +
      "re.framework.starter.control.protobuf.Re" +
      "questDto\032;.com.acmedcare.framework.start" +
      "er.control.protobuf.ResultDto\"\000\022\203\001\n\004stop" +
      "\022<.com.acmedcare.framework.starter.contr" +
      "ol.protobuf.RequestDto\032;.com.acmedcare.f" +
      "ramework.starter.control.protobuf.Result" +
      "Dto\"\000\022\207\001\n\007getInfo\022<.com.acmedcare.framew" +
      "ork.starter.control.protobuf.RequestDto\032" +
      "<.com.acmedcare.framework.starter.contro" +
      "l.protobuf.ServiceDto\"\000BA\n0com.acmedcare" +
      ".framework.starter.control.protobufB\013Dev" +
      "OpsProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_acmedcare_framework_starter_control_protobuf_RequestDto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_acmedcare_framework_starter_control_protobuf_RequestDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_acmedcare_framework_starter_control_protobuf_RequestDto_descriptor,
        new String[] { "Data", });
    internal_static_com_acmedcare_framework_starter_control_protobuf_ResultDto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_acmedcare_framework_starter_control_protobuf_ResultDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_acmedcare_framework_starter_control_protobuf_ResultDto_descriptor,
        new String[] { "Success", });
    internal_static_com_acmedcare_framework_starter_control_protobuf_ServiceDto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_acmedcare_framework_starter_control_protobuf_ServiceDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_acmedcare_framework_starter_control_protobuf_ServiceDto_descriptor,
        new String[] { "Name", "Ip", "Port", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
