// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: controller.proto

package com.acmedcare.framework.starter.control.protobuf;

public final class DevOpsProto {
  private DevOpsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_acmedcare_framework_starter_control_protobuf_RequestDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_acmedcare_framework_starter_control_protobuf_RequestDto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_acmedcare_framework_starter_control_protobuf_ResultDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_acmedcare_framework_starter_control_protobuf_ResultDto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_acmedcare_framework_starter_control_protobuf_ServiceDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_acmedcare_framework_starter_control_protobuf_ServiceDto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020controller.proto\0220com.acmedcare.framew" +
      "ork.starter.control.protobuf\"\032\n\nRequestD" +
      "to\022\014\n\004data\030\001 \001(\t\"\034\n\tResultDto\022\017\n\007success" +
      "\030\001 \001(\010\"3\n\nServiceDto\022\014\n\004name\030\001 \001(\t\022\n\n\002ip" +
      "\030\002 \001(\t\022\013\n\003por\030\003 \001(\t2\260\004\n\020DevOpsController" +
      "\022\204\001\n\005check\022<.com.acmedcare.framework.sta" +
      "rter.control.protobuf.RequestDto\032;.com.a" +
      "cmedcare.framework.starter.control.proto" +
      "buf.ResultDto\"\000\022\204\001\n\005start\022<.com.acmedcar" +
      "e.framework.starter.control.protobuf.Req" +
      "uestDto\032;.com.acmedcare.framework.starte" +
      "r.control.protobuf.ResultDto\"\000\022\203\001\n\004stop\022" +
      "<.com.acmedcare.framework.starter.contro" +
      "l.protobuf.RequestDto\032;.com.acmedcare.fr" +
      "amework.starter.control.protobuf.ResultD" +
      "to\"\000\022\207\001\n\007getInfo\022<.com.acmedcare.framewo" +
      "rk.starter.control.protobuf.RequestDto\032<" +
      ".com.acmedcare.framework.starter.control" +
      ".protobuf.ServiceDto\"\000BA\n0com.acmedcare." +
      "framework.starter.control.protobufB\013DevO" +
      "psProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_acmedcare_framework_starter_control_protobuf_RequestDto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_acmedcare_framework_starter_control_protobuf_RequestDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_acmedcare_framework_starter_control_protobuf_RequestDto_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_com_acmedcare_framework_starter_control_protobuf_ResultDto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_acmedcare_framework_starter_control_protobuf_ResultDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_acmedcare_framework_starter_control_protobuf_ResultDto_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_com_acmedcare_framework_starter_control_protobuf_ServiceDto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_acmedcare_framework_starter_control_protobuf_ServiceDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_acmedcare_framework_starter_control_protobuf_ServiceDto_descriptor,
        new java.lang.String[] { "Name", "Ip", "Por", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
