// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: controller.proto

package com.acmedcare.framework.starter.control.protobuf;

public interface RequestDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.acmedcare.framework.starter.control.protobuf.RequestDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string data = 1;</code>
   * @return The data.
   */
  String getData();
  /**
   * <code>string data = 1;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
