// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: controller.proto

package com.acmedcare.framework.starter.control.protobuf;

public interface ResultDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.acmedcare.framework.starter.control.protobuf.ResultDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();
}
