// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: controller.proto

package com.acmedcare.framework.starter.control.protobuf;

public interface ResultDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.acmedcare.framework.starter.control.protobuf.ResultDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string success = 1;</code>
   * @return The success.
   */
  String getSuccess();
  /**
   * <code>string success = 1;</code>
   * @return The bytes for success.
   */
  com.google.protobuf.ByteString
      getSuccessBytes();
}
