// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: controller.proto

package com.acmedcare.framework.starter.control.protobuf;

public interface ServiceDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.acmedcare.framework.starter.control.protobuf.ServiceDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string ip = 2;</code>
   * @return The ip.
   */
  java.lang.String getIp();
  /**
   * <code>string ip = 2;</code>
   * @return The bytes for ip.
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>string por = 3;</code>
   * @return The por.
   */
  java.lang.String getPor();
  /**
   * <code>string por = 3;</code>
   * @return The bytes for por.
   */
  com.google.protobuf.ByteString
      getPorBytes();
}
