// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: controller.proto

package com.acmedcare.framework.starter.control.protobuf;

public interface ServiceDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.acmedcare.framework.starter.control.protobuf.ServiceDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string ip = 2;</code>
   * @return The ip.
   */
  String getIp();
  /**
   * <code>string ip = 2;</code>
   * @return The bytes for ip.
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>string port = 3;</code>
   * @return The port.
   */
  String getPort();
  /**
   * <code>string port = 3;</code>
   * @return The bytes for port.
   */
  com.google.protobuf.ByteString
      getPortBytes();
}
